services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"  # Expose PostgreSQL on port 5433 for testing
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready  -d test_db -U test_user"]
      interval: 10s
      retries: 10

volumes:
  pg_data:
