name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Habilitar ejecución manual

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Init migrations for test database
        run: |
          export $(cat .env.test | xargs) && npx prisma migrate dev --name init --schema=prisma/schema.prisma

      - name: Deploy migrations for test database
        run: |
          export $(cat .env.test | xargs) && npx prisma migrate deploy --schema=prisma/schema.prisma

      - name: Run unit tests
        run: npm run test:unit

      - name: Run e2e tests
        run: npm run test:e2e

      # - name: Build Docker image
      #   run: docker build -t my-nest-app .

      # - name: Run Docker container (production)
      #   run: docker-compose -f docker-compose.prod.yml up -d

      # - name: Health check (production)
      #   run: curl --fail http://localhost:3000/health

  sonar-analysis:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SonarQube Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner.zip
          export PATH=$PATH:$PWD/sonar-scanner-4.6.2.2472-linux/bin

      - name: Run SonarQube Analysis
        env:
          SONAR_HOST_URL: "http://localhost:9000"
          SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-nest-app \
            -Dsonar.sources=./src \
            -Dsonar.tests=./test \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

  taurus-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Install Taurus
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip && pip3 install bzt

      - name: Run Load Test with Taurus
        run: |
          bzt load_test.yml
